Remove un-used handshakes
ChainSafe/js-libp2p-noise pull request #177
Opened 2022-08-02 17:57 UTC by dapplion

As discussed offline, not need to keep code that will probably be never used

2022-08-02 18:09 UTC, mpetrunic commented
@dapplion lint errors^^

2022-08-02 19:00 UTC, dapplion commented
> @dapplion lint errors^^

So I had to disable prettier for this repo because it completely changed everything. But then there's this linter? So in Lodestar prettier is connected to the linter such that VSCode can understand what the linter wants and apply that automatically for you if you have  `{ "editor.formatOnSave": false }`. How do you handle that with aegir?

2022-08-03 07:23 UTC, mpetrunic commented
> > @dapplion lint errors^^
> 
> So I had to disable prettier for this repo because it completely changed everything. But then there's this linter? So in Lodestar prettier is connected to the linter such that VSCode can understand what the linter wants and apply that automatically for you if you have `{ "editor.formatOnSave": true }`. How do you handle that with aegir?

For me it detected. Do you have this checked: 
![image](https://user-images.githubusercontent.com/8836210/182548648-97971d2f-b280-4140-a036-6c2d514395cc.png)

2022-08-03 07:23 UTC, mpetrunic commented
@dapplion since this is breaking change, should we wait with releasing until we land changed connection encrypted interface?

2022-08-03 07:24 UTC, mpetrunic commented
> @dapplion since this is breaking change, should we wait with releasing until we land changed connection encrypted interface?

@wemeetagain^^

2022-08-03 13:37 UTC, wemeetagain commented
yea lets wait, should happen soon

2022-08-03 13:40 UTC, mpetrunic requested changes

2022-08-03 13:40 UTC, mpetrunic commented on src/noise.ts
> +      if (handshake.remotePeer) {
this condition and keycache store should be removed

2022-08-07 14:39 UTC, dapplion commented
> > > @dapplion lint errors^^
> > 
> > 
> > So I had to disable prettier for this repo because it completely changed everything. But then there's this linter? So in Lodestar prettier is connected to the linter such that VSCode can understand what the linter wants and apply that automatically for you if you have `{ "editor.formatOnSave": true }`. How do you handle that with aegir?
> 
> For me it detected. Do you have this checked: ![image](https://user-images.githubusercontent.com/8836210/182548648-97971d2f-b280-4140-a036-6c2d514395cc.png)

Still not working, I can DM to debug

2022-08-08 09:01 UTC, mpetrunic commented
@achingbrain aegir dep-check is passing without warnings or errors for unused prod dependencies. Is that normal?

2022-08-10 13:45 UTC, mpetrunic approved these changes

2022-08-10 13:45 UTC, merged