chore: update protons and connection encryption interface
ChainSafe/js-libp2p-noise pull request #193
Opened 2022-08-10 14:23 UTC by mpetrunic

2022-08-10 15:58 UTC, achingbrain approved these changes

2022-08-10 20:08 UTC, wemeetagain commented
this is a breaking change, changing the PR title

2022-08-10 20:08 UTC, wemeetagain submitted a review, later dismissed

2022-08-10 20:36 UTC, mpetrunic commented
> this is a breaking change, changing the PR title

What is breaking change here? 😅

2022-08-11 08:54 UTC, achingbrain requested changes
This needs one final regeneration of the protobuf files with protons at `5.1.0` but then it should be good to go and will unblock https://github.com/libp2p/js-libp2p/pull/1335

2022-08-11 08:54 UTC, achingbrain commented on package.json
> +    "protons": "^5.0.0",
```suggestion
    "protons": "^5.1.0",
```

2022-08-11 08:54 UTC, achingbrain commented on package.json
> +    "protons-runtime": "^3.0.1",
```suggestion
    "protons-runtime": "^3.1.0",
```

2022-08-11 08:54 UTC, achingbrain commented on package.json
>      "it-pb-stream": "^2.0.1",
```suggestion
    "it-pb-stream": "^2.0.2",
```

2022-08-11 09:22 UTC, merged